In [1]:
import numpy as np
import pandas as pd

In [1]:
df=pd.read_csv('/content/Products.csv')
df.sample(10)

NameError: name 'pd' is not defined

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177272 entries, 0 to 177271
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             177272 non-null  int64
 1   id                     177272 non-null  int64
 2   categories             177272 non-null  object
 3   gender                 177272 non-null  object
 4   timestamp              177272 non-null  object
 5   url                    177272 non-null  object
 6   source                 177272 non-null  object
 7   merchant               177272 non-null  object
 8   country                177272 non-null  object
 9   name                   177272 non-null  object
 10  description            177272 non-null  object
 11  brand                  177272 non-null  object
 12  sustainability_labels  177272 non-null  object
 13  price                  177272 non-null  float64
 14  currency               177272 non-null  object
 15  image_urls             177272 non-null  object
 16  consumer_lifestage     177272 non-null  object
 17  colors                 177272 non-null  object
 18  sizes                  31251 non-null   object
 19  gtin                   0 non-null       float64
 20  asin                   44887 non-null   object
 21  product_text           175311 non-null  object
dtypes: float64(2), int64(2), object(18)
memory usage: 29.8+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0               0
id                       0
categories               0
gender                   0
timestamp                0
url                      0
source                   0
merchant                 0
country                  0
name                     0
description              0
brand                    0
sustainability_labels    0
price                    0
currency                 0
image_urls               0
consumer_lifestage       0
colors                   0
sizes                    0
gtin                     0
asin                     0
product_text             0
dtype: int64

In [ ]:
df['asin'].fillna('Not Available',inplace=True)

<ipython-input-25-17317a5aed64>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['asin'].fillna('Not Available',inplace=True)

In [ ]:
df['product_text'].fillna('Not Available',inplace=True)

<ipython-input-37-0cf4b7c81125>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['product_text'].fillna('Not Available',inplace=True)

In [ ]:
df['gtin'] = df['gtin'].astype(object)
df['gtin'].fillna('Not Available',inplace=True)

<ipython-input-32-01abc4518691>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gtin'].fillna('Not Available',inplace=True)

In [ ]:
df['gender'].unique()

array(['FEMALE', nan, 'MALE', 'UNISEX'], dtype=object)

In [ ]:
df['sizes'].fillna('All',inplace=True)

<ipython-input-19-7be2cf72af20>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sizes'].fillna('All',inplace=True)

In [ ]:
df['colors'].fillna('All',inplace=True)

<ipython-input-16-7fbe980b7370>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['colors'].fillna('All',inplace=True)

In [ ]:
df['gender'].fillna('UNISEX',inplace=True)

<ipython-input-10-e02f87b2c8e1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna('UNISEX',inplace=True)

In [ ]:
df['consumer_lifestage'].fillna('All',inplace=True)

<ipython-input-14-b307bec56293>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['consumer_lifestage'].fillna('All',inplace=True)

In [ ]:
df['description'].fillna('NO Description Available',inplace=True)

<ipython-input-12-c3d0c5ac7520>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['description'].fillna('NO Description Available',inplace=True)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Combine relevant text fields for similarity matching
df['product_text'] = df['name'] + " " + df['description']

# Create TF-IDF vectors for text similarity
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(df['product_text'])

In [ ]:
def find_similar_products(input_product, df, tfidf_matrix, vectorizer, top_n=5):
    """
    Find top_n most similar eco-friendly products to the input product

    Args:
    input_product (dict): Product details from the website with keys like 'name', 'description', etc.
    df: Your greenDB DataFrame
    tfidf_matrix: Precomputed TF-IDF matrix
    vectorizer: Fitted TF-IDF vectorizer
    top_n: Number of similar products to return

    Returns:
    DataFrame with top_n similar products
    """
    # Combine input product text in same way as training data
    input_text = input_product.get('name', '') + " " + \
                 input_product.get('description', '')

    # Vectorize the input text
    input_vector = vectorizer.transform([input_text])

    # Calculate cosine similarities
    similarities = cosine_similarity(input_vector, tfidf_matrix)

    # Get indices of top_n most similar products
    similar_indices = similarities.argsort()[0][-top_n:][::-1]

    # Return the most similar products
    return df.iloc[similar_indices].copy()

In [ ]:
def rank_products(similar_products):
    """
    Rank similar products by multiple criteria to find the "best" one

    Args:
    similar_products: DataFrame of similar products

    Returns:
    The single best product to highlight
    """
    # Add scoring for different factors
    similar_products['score'] = 0

    # Higher price might mean better quality (adjust weights as needed)
    similar_products['score'] += similar_products['price'] * 0.1

    # More sustainability labels is better
    similar_products['score'] += similar_products['sustainability_labels'].str.count(',') * 10

    # Higher in search results is better
    similar_products['score'] += (len(similar_products) - similar_products.index) * 5

    # Return the product with highest score
    return similar_products.loc[similar_products['score'].idxmax()]

In [ ]:
example_product = {
    "name": "Classic Straight Fit Jeans for Men",
    "description": "Mid-waist straight fit jeans made with 100% cotton. Five-pocket styling with zip fly and button closure. Machine washable.",
    "brand": "FashionHub",
    "category": "Clothing > Men > Jeans",
    "price": 45.99,
    "currency": "USD"
}

In [ ]:
similar_eco_products = find_similar_products(example_product, df, tfidf_matrix, vectorizer)
similar_eco_products

,Unnamed: 0,id,categories,gender,timestamp,url,source,merchant,country,name,...,sustainability_labels,price,currency,image_urls,consumer_lifestage,colors,sizes,gtin,asin,product_text
114787,2227579,9479158,['SOCKS'],FEMALE,2023-02-17 18:00:57.019642,https://www.zalando.co.uk/na-kd-tall-button-cl...,zalando,zalando,GB,BUTTON CLOSURE STRAIGHT TALL - Straight leg je...,...,['certificate:OTHER'],32.00,GBP,['https://img01.ztat.net/article/spp-media-p1/...,ADULT,['mid blue/blue'],All,Not Available,Not Available,BUTTON CLOSURE STRAIGHT TALL - Straight leg je...
125853,2247907,9358040,['SOCKS'],FEMALE,2023-02-17 18:00:57.019642,https://www.zalando.co.uk/na-kd-button-closure...,zalando,zalando,GB,BUTTON CLOSURE - Straight leg jeans - mid blue,...,['certificate:OTHER'],37.00,GBP,['https://img01.ztat.net/article/spp-media-p1/...,ADULT,['mid blue/blue'],All,Not Available,Not Available,BUTTON CLOSURE - Straight leg jeans - mid blue...
128152,2278745,9087897,['SOCKS'],FEMALE,2023-02-10 18:00:47.596703,https://www.zalando.co.uk/soft-rebels-waist-lo...,zalando,zalando,GB,WAIST LONG STRAIGHT - Straight leg jeans - mid...,...,['certificate:OTHER'],60.00,GBP,['https://img01.ztat.net/article/spp-media-p1/...,ADULT,['mid washed blue/blue denim'],All,Not Available,Not Available,WAIST LONG STRAIGHT - Straight leg jeans - mid...
96831,2185948,9602713,['JEANS'],FEMALE,2023-02-24 18:00:15.246235,https://www.zalando.co.uk/marc-opolo-trouser-s...,zalando,zalando,GB,TROUSER STRAIGHT FIT CROPPED LENGTH HIGH WAIST...,...,['certificate:ORGANIC_CONTENT_STANDARD_100'],139.99,GBP,['https://img01.ztat.net/article/spp-media-p1/...,ADULT,['mid stone wash/stone'],All,Not Available,Not Available,TROUSER STRAIGHT FIT CROPPED LENGTH HIGH WAIST...
101595,2197129,9576018,['JEANS'],FEMALE,2023-02-24 18:00:15.246235,https://www.zalando.co.uk/pepe-jeans-venus-str...,zalando,zalando,GB,VENUS STRAIGHT FIT LOW WAIST - Straight leg je...,...,['certificate:OTHER'],89.99,GBP,['https://img01.ztat.net/article/spp-media-p1/...,ADULT,['blue/blue denim'],All,Not Available,Not Available,VENUS STRAIGHT FIT LOW WAIST - Straight leg je...

In [ ]:
df['url'][0]

'https://www.amazon.co.uk/Sloggi-Womens-Mini-Briefs-Combination/dp/B07WD3ML9S/ref=sr_1_146'